name: your-service
services:
  fixed-term-track-web-server:
    image: mesmur/fixed-term-track-web-server:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
